const topics = [
  'Agriculture',
  'Neuroscience',
  'Human Longevity',
  'Renewable Energy',
  'Mobility',
  'Manufacturing',
  'Nanotechnology',
  'Semiconductors',
  'Software',
  'Blockchain',
  'Space Science',
  'Virtual Reality',
  'Quantum Technologies',
  'Ecology',
  'Robotics',
  'Digital Health',
  'Medical Devices',
  'Electronics',
  'Photonics',
  'Artificial Intelligence',
  'Materials',
  'Climate Research',
  'Psychology',
  'Economics',
  'Social Sciences',
  'Pharmaceuticals',
];

export default topics;
